# Note: indendentation is important
# Verify formatting here: https://yaml-online-parser.appspot.com/

# This file contains configuration information for the Log Insight plugin

# WARNING: Log Insight sends the username and password in clear text (confirmed on 8.4)
# Log Insight supports a username and password, in two different headers
config:
  webhook_secret: 'Password'
  webhook_user: 'chatbot'
  auth_header: 'Authorization-User'
  auth_header_secret: 'Authorization-Password'
  sql_table: 'loginsight_events'
  chat_id: '19:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@thread.v2'

